monitor-ui/src/Covid19.Monitor.Ui/Models/BackendGroupedCasesResponse.cs
using System.Text.Json.Serialization;

namespace Covid19.Monitor.Ui.Models
{
    public class BackendGroupedCasesResponse
    {
        [JsonPropertyName("month")]
        public int Month { get; set; }
        
        [JsonPropertyName("currentCases")]
        public int? CurrentCases { get; set; }
        
        [JsonPropertyName("newCases")]
        public int? NewCases { get; set; }
        
        [JsonPropertyName("currentDeaths")]
        public int? CurrentDeaths { get; set; }
        
        [JsonPropertyName("newDeaths")]
        public int? NewDeaths { get; set; }
    }
}

monitor-ui/src/Covid19.Monitor.Ui/Models/ErrorViewModel.cs
using System;

namespace Covid19.Monitor.Ui.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

monitor-ui/src/Covid19.Monitor.Ui/Models/PanelViewModel.cs
using System.Collections.Generic;
using System.Text.Json;

namespace Covid19.Monitor.Ui.Models
{
    public class PanelViewModel
    {
        public string Message { get; set; }
        public string ClientRemoteIpv4 { get; set; }
        public int[] NewCases { get; set; }
        public int[] CurrentCases { get; set; }
        public int[] NewDeaths { get; set; }
        public int[] CurrentDeaths { get; set; }
        public List<TableViewModel> Cases { get; set; }
        public List<TableViewModel>  Deaths { get; set; }
    }
}

monitor-ui/src/Covid19.Monitor.Ui/Models/TableViewModel.cs
namespace Covid19.Monitor.Ui.Models
{
    public class TableViewModel
    {
        public string Estado { get; set; }
        public int? Atual { get; set; }
        public int? Novos { get; set; }
    }
}

monitor-ui/src/Covid19.Monitor.Ui/Controllers/Covid19TestController.cs
using Microsoft.AspNetCore.Mvc;

namespace Covid19.Monitor.Ui.Controllers
{
    [Route("covid-19-test")]
    public class Covid19TestController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return View();
        }
    }
}

monitor-ui/src/Covid19.Monitor.Ui/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Covid19.Monitor.Ui.Models;

namespace Covid19.Monitor.Ui.Controllers
{
    [Route("home")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

monitor-ui/src/Covid19.Monitor.Ui/Controllers/MedicalConsultationController.cs
using Microsoft.AspNetCore.Mvc;

namespace Covid19.Monitor.Ui.Controllers
{
    [Route("medical-consultation")]
    public class MedicalConsultationController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return View();
        }
    }
}

monitor-ui/src/Covid19.Monitor.Ui/Controllers/PanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Covid19.Monitor.Ui.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Covid19.Monitor.Ui.Controllers
{
    [Route("panel")]
    public class PanelController : Controller
    {
        private readonly ConnectionInfo _connection;
        private readonly Uri _backendUri;
        private readonly string[] _regionCodes;

        public PanelController(IHttpContextAccessor httpContextAccessor, IConfiguration configuration)
        {
            _connection = httpContextAccessor.HttpContext.Connection;
            _backendUri = new Uri(configuration.GetValue<string>("BackendUrl"));
            _regionCodes = new[]
            {
                "AC","AL","AP","AM","BA","CE","DF","ES","GO","MA",
                "MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN",
                "RS","RO","RR","SC","SP","SE","TO"
            };
        }

        public async Task<IActionResult> Index([FromServices] IConfiguration configuration)
        {
            var model = new PanelViewModel
            {
                ClientRemoteIpv4 = _connection.RemoteIpAddress.MapToIPv4().ToString(),
                CurrentCases = new int[12],
                NewCases = new int[12],
                CurrentDeaths = new int[12],
                NewDeaths = new int[12],
                Cases = new List<TableViewModel>(),
                Deaths = new List<TableViewModel>()
            };

            try
            {
                using var httpClient = new HttpClient
                {
                    BaseAddress = _backendUri
                };

                var jsonAllCases = await httpClient.GetStringAsync("api/cases/month");
                var resultAllCases = JsonSerializer.Deserialize<List<BackendGroupedCasesResponse>>(jsonAllCases);

                foreach (var item in resultAllCases)
                {
                    model.CurrentCases[item.Month - 1] = item.CurrentCases ?? 0;
                    model.NewCases[item.Month - 1] = item.NewCases ?? 0;
                    model.CurrentDeaths[item.Month - 1] = item.CurrentDeaths ?? 0;
                    model.NewDeaths[item.Month - 1] = item.NewDeaths ?? 0;
                }

                foreach (var regionCode in _regionCodes)
                {
                    var json = await httpClient.GetStringAsync($"api/cases/{regionCode}/month");
                    var result = JsonSerializer.Deserialize<List<BackendGroupedCasesResponse>>(json);
                    var info = result.OrderByDescending(r => r.Month).FirstOrDefault();
                    model.Cases.Add(new TableViewModel
                    {
                        Estado = regionCode,
                        Atual = info?.CurrentCases ?? 0,
                        Novos = info?.NewCases ?? 0
                    });
                    
                    model.Deaths.Add(new TableViewModel
                    {
                        Estado = regionCode,
                        Atual = info?.CurrentDeaths ?? 0,
                        Novos = info?.NewDeaths ?? 0
                    });
                }
            }
            catch (Exception e)
            {
                model.Message = e.Message;
            }

            return View(model);
        }
    }
}

monitor-ui/src/Covid19.Monitor.Ui/Controllers/StayHomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Covid19.Monitor.Ui.Controllers
{
    [Route("stay-home")]
    public class StayHomeController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return View();
        }
    }
}

monitor-ui/src/Covid19.Monitor.Ui/Controllers/SupplyController.cs
using Microsoft.AspNetCore.Mvc;

namespace Covid19.Monitor.Ui.Controllers
{
    [Route("supply")]
    public class SupplyController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return View();
        }
    }
}

monitor-ui/src/Covid19.Monitor.Ui/Views/Covid19Test/Index.cshtml
@{
    ViewData["Icon"] = "fa-vial";
    ViewData["Title"] = "Testes Covid-19";
}

monitor-ui/src/Covid19.Monitor.Ui/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<table class="table table-sm table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Header</th>
            <th>Header</th>
            <th>Header</th>
            <th>Header</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1,001</td>
            <td>Lorem</td>
            <td>ipsum</td>
            <td>dolor</td>
            <td>sit</td>
        </tr>
        <tr>
            <td>1,002</td>
            <td>amet</td>
            <td>consectetur</td>
            <td>adipiscing</td>
            <td>elit</td>
        </tr>
        <tr>
            <td>1,003</td>
            <td>Integer</td>
            <td>nec</td>
            <td>odio</td>
            <td>Praesent</td>
        </tr>
        <tr>
            <td>1,003</td>
            <td>libero</td>
            <td>Sed</td>
            <td>cursus</td>
            <td>ante</td>
        </tr>
        <tr>
            <td>1,004</td>
            <td>dapibus</td>
            <td>diam</td>
            <td>Sed</td>
            <td>nisi</td>
        </tr>
        <tr>
            <td>1,005</td>
            <td>Nulla</td>
            <td>quis</td>
            <td>sem</td>
            <td>at</td>
        </tr>
        <tr>
            <td>1,006</td>
            <td>nibh</td>
            <td>elementum</td>
            <td>imperdiet</td>
            <td>Duis</td>
        </tr>
        <tr>
            <td>1,007</td>
            <td>sagittis</td>
            <td>ipsum</td>
            <td>Praesent</td>
            <td>mauris</td>
        </tr>
        <tr>
            <td>1,008</td>
            <td>Fusce</td>
            <td>nec</td>
            <td>tellus</td>
            <td>sed</td>
        </tr>
        <tr>
            <td>1,009</td>
            <td>augue</td>
            <td>semper</td>
            <td>porta</td>
            <td>Mauris</td>
        </tr>
        <tr>
            <td>1,010</td>
            <td>massa</td>
            <td>Vestibulum</td>
            <td>lacinia</td>
            <td>arcu</td>
        </tr>
        <tr>
            <td>1,011</td>
            <td>eget</td>
            <td>nulla</td>
            <td>Class</td>
            <td>aptent</td>
        </tr>
        <tr>
            <td>1,012</td>
            <td>taciti</td>
            <td>sociosqu</td>
            <td>ad</td>
            <td>litora</td>
        </tr>
        <tr>
            <td>1,013</td>
            <td>torquent</td>
            <td>per</td>
            <td>conubia</td>
            <td>nostra</td>
        </tr>
        <tr>
            <td>1,014</td>
            <td>per</td>
            <td>inceptos</td>
            <td>himenaeos</td>
            <td>Curabitur</td>
        </tr>
        <tr>
            <td>1,015</td>
            <td>sodales</td>
            <td>ligula</td>
            <td>in</td>
            <td>libero</td>
        </tr>
    </tbody>
</table>

monitor-ui/src/Covid19.Monitor.Ui/Views/MedicalConsultation/Index.cshtml
@{
    ViewData["Icon"] = "fa-stethoscope";
    ViewData["Title"] = "Consulta Médica On-line";
}

monitor-ui/src/Covid19.Monitor.Ui/Views/Panel/Index.cshtml
@using System.Text.Json
@model PanelViewModel

@{
    ViewData["Icon"] = "fa-chart-line";
    ViewData["Title"] = "Painel";
}

@section Scripts
{
    <script>
    !(function ($) {
        'use strict'
    
        let presets = {
            red: 'rgb(255, 99, 132)',
            orange: 'rgb(255, 159, 64)',
            yellow: 'rgb(255, 205, 86)',
            green: 'rgb(75, 192, 192)',
            blue: 'rgb(54, 162, 235)',
            purple: 'rgb(153, 102, 255)',
            grey: 'rgb(201, 203, 207)',
            black: 'rgb(0,0,0)'
        };
        
        let ctxCases = document.getElementById('casos').getContext('2d');
        let ctsDeaths = document.getElementById('obitos').getContext('2d');
        
        let transparentize = (color, opacity) => {
            let alpha = opacity === undefined ? 0.5 : 1 - opacity;
            return Color(color).alpha(alpha).rgbString();
        };   
        
        let chartCases = new Chart(ctxCases, {
            type: 'line',
            data: {
                labels: ['JAN', 'FEV', 'MAR', 'ABR', 'MAI', 'JUN', 'JUL', 'AGO', 'SET', 'OUT', 'NOV', 'DEZ'],
                datasets: [{
                    label: 'Casos',
                    backgroundColor: transparentize(presets.purple),
                    borderColor: presets.purple,
                    fill: true,
                    data: @JsonSerializer.Serialize(Model.CurrentCases),
                    yAxisID: 'y-axis-1'
                },{
                    label: 'Novos Casos',
                    backgroundColor: transparentize(presets.green),
                    borderColor: presets.green,
                    fill: true,
                    data: @JsonSerializer.Serialize(Model.NewCases),
                    yAxisID: 'y-axis-2'
                }]
            },
            options: {
                responsive: true,
                hoverMode: 'index',
                stacked: false,
                title: {
                    display: true,
                    text: 'Casos x Novos Casos'
                },
                scales: {
                    yAxes: [{
                        type: 'linear',
                        display: true,
                        position: 'left',
                        id: 'y-axis-1',
                    }, {
                        type: 'linear',
                        display: true,
                        position: 'right',
                        id: 'y-axis-2',
                        gridLines: {
                            drawOnChartArea: false,
                        },
                    }],
                }
            }
        });

        
        let chartDeaths = new Chart(ctsDeaths, {
            type: 'line',
            data: {
                labels: ['JAN', 'FEV', 'MAR', 'ABR', 'MAI', 'JUN', 'JUL', 'AGO', 'SET', 'OUT', 'NOV', 'DEZ'],
                datasets: [{
                    label: 'Óbitos',
                    backgroundColor: transparentize(presets.black),
                    borderColor: presets.black,
                    fill: true,
                    data: @JsonSerializer.Serialize(Model.CurrentDeaths),
                    yAxisID: 'y-axis-2'
                },{
                    label: 'Novos Óbitos',
                    backgroundColor: transparentize(presets.red),
                    borderColor: presets.red,
                    fill: true,
                    data: @JsonSerializer.Serialize(Model.NewDeaths),
                    yAxisID: 'y-axis-1'
                }]
            },
            options: {
                responsive: true,
                hoverMode: 'index',
                stacked: false,
                title: {
                    display: true,
                    text: 'Óbitos x Novos óbitos'
                },
                scales: {
                    yAxes: [{
                        type: 'linear',
                        display: true,
                        position: 'left',
                        id: 'y-axis-1',
                    }, {
                        type: 'linear',
                        display: true,
                        position: 'right',
                        id: 'y-axis-2',
                        gridLines: {
                            drawOnChartArea: false,
                        },
                    }],
                }
            }
        });        
    
    }(window.jQuery));
    </script>
}


<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">
        <i class="fad fa-virus"></i>
        Alerta de COVID-19 na sua região
        <i class="fad fa-virus"></i>
    </h4>
    @Model
    Foi identificado que você está em <strong>Belo Horizonte</strong> fique atento, pois foram notificados <strong>151,000</strong> casos na sua região, sendo <strong>25</strong> no dia de hoje.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="row">
    <div class="col">
        <div class="card">
            <h5 class="card-header"><i class="fad fa-hospital-user"></i>&nbsp;Casos</h5>
            <div class="card-body">
                <small>fonte: Secretarias Estaduais de Saúde (SES).</small>
                <canvas id="casos" height="150"></canvas>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Estado</th>
                                <th scope="col">Total de cados </th>
                                <th scope="col">Novos casos (até ontem)</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Cases)
                            {
                                <tr>
                                    <td>@item.Estado</td>
                                    <td>@item.Atual</td>
                                    <td>@item.Novos</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h5 class="card-header"><i class="fad fa-tombstone"></i>&nbsp;Óbitos</h5>
            <div class="card-body">
                <small>fonte: Registros em cartórios e Portal da Transparência do Registro Civil.</small>
                <canvas id="obitos" height="150"></canvas>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Estado</th>
                                <th scope="col">Total de óbitos</th>
                                <th scope="col">Novos óbitos (até ontem)</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Deaths)
                            {
                                <tr>
                                    <td>@item.Estado</td>
                                    <td>@item.Atual</td>
                                    <td>@item.Novos</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

monitor-ui/src/Covid19.Monitor.Ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
        <title>@ViewData["Title"] - Covid19.Monitor.Ui</title>
        <link href="~/lib/vendor/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous"/>
        <link href="~/lib/vendor/Chart.min.css" rel="stylesheet" crossorigin="anonymous"/>
        <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" crossorigin="anonymous"/>
        <link href="~/css/site.css" rel="stylesheet" crossorigin="anonymous"/>
    </head>
    <body>
        <nav class="bg-dark flex-md-nowrap navbar navbar-dark p-0 shadow sticky-top">
            <a class="col-lg-2 col-md-3 mr-0 navbar-brand px-3" href="#"><i class="fas fa-virus"></i> Covid-19 Monitor</a>
            <button aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation" class="collapsed d-md-none navbar-toggler position-absolute" data-target="#sidebarMenu" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="text-white">
                <h1 class="h3"><i class="fad @ViewData["Icon"]"></i> @ViewData["Title"]</h1>
            </div>

            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group mr-2">
                    <button class="btn btn-outline-secondary btn-sm" type="button">
                        <i class="fas fa-share-alt"></i>
                        Compartilhar
                    </button>
                    <button class="btn btn-outline-secondary btn-sm" type="button" style="border-left: none;">
                        <i class="fas fa-file-download"></i>
                        Baixar
                    </button>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <nav class="bg-light collapse col-lg-2 col-md-3 d-md-block sidebar" id="sidebarMenu">
                    <div class="pt-3 sidebar-sticky">

                        <h6 class="align-items-center d-flex justify-content-between mb-1 mt-0 px-3 sidebar-heading text-muted">
                            <span>Menu</span>
                        </h6>

                        <ul class="flex-column nav">
                            <li class="nav-item">
                                <a data-id="panel" class="nav-link" asp-controller="Panel" asp-action="Index">
                                    <i class="fad fa-chart-line"></i>
                                    Painel
                                </a>
                            </li>
                            <li class="nav-item">
                                <a data-id="supply" class="nav-link" asp-controller="Supply" asp-action="Index">
                                    <i class="fad fa-pump-soap"></i>
                                    Suprimentos
                                </a>
                            </li>
                            <li class="nav-item">
                                <a data-id="medical-consultation" class="nav-link" asp-controller="MedicalConsultation" asp-action="Index">
                                    <i class="fad fa-stethoscope"></i>
                                    Consulta On-line
                                </a>
                            </li>
                            <li class="nav-item">
                                <a data-id="covid-19-test" class="nav-link" asp-controller="Covid19Test" asp-action="Index">
                                    <i class="fad fa-vial"></i>
                                    Testes para Covid-19
                                </a>
                            </li>
                            <li class="nav-item">
                                <a data-id="stay-home" class="nav-link" asp-controller="StayHome" asp-action="Index">
                                    <i class="fad fa-home"></i>
                                    Fique em casa
                                </a>
                            </li>
                        </ul>

                    </div>
                </nav>

                <main class="col-lg-10 col-md-9 ml-sm-auto px-md-4 mt-3" role="main">
                    @RenderBody()
                </main>
            </div>
        </div>
        <script src="~/lib/vendor/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="~/lib/vendor/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="~/lib/vendor/Chart.min.js" crossorigin="anonymous"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>

monitor-ui/src/Covid19.Monitor.Ui/Views/StayHome/Index.cshtml
@{
    ViewData["Icon"] = "fa-home";
    ViewData["Title"] = "Fique em casa";
}

<h4>Fique em casa</h4>

<p>
    Ensine seus filhos a importância do uso do alcool em gel, utilize o alcool para matar o coronavirus.
    Mova com as setas do teclado e dispara alcool em gem com a barra de espaço.
</p>

<div id="gamecontainer">
    <canvas id="gameCanvas"></canvas>
</div>

<img id="shipSkin" src="img/alcool.gif" width="0" height="0" alt=""/>
<img id="invaderSkin" src="img/virus.gif" width="0" height="0" alt=""/>

<script src="js/spaceinvaders.js"></script>
<script>

            //  Setup the canvas.
            var canvas = document.getElementById("gameCanvas");
            canvas.width = 800;
            canvas.height = 600;

            //  Create the game.
            var game = new Game();

            //  Initialise it with the game canvas.
            game.initialise(canvas);

            //  Start the game.
            game.start();

            //  Listen for keyboard events.
            window.addEventListener("keydown", function keydown(e) {
                var keycode = e.which || window.event.keycode;
                //  Supress further processing of left/right/space (37/29/32)
                if(keycode == 37 || keycode == 39 || keycode == 32) {
                    e.preventDefault();
                }
                game.keyDown(keycode);

            });
            window.addEventListener("keyup", function keydown(e) {
                var keycode = e.which || window.event.keycode;
                game.keyUp(keycode);
            });

            window.addEventListener("touchstart", function (e) {
                game.touchstart(e);
            }, false);
 
            window.addEventListener('touchend', function(e){
                game.touchend(e);
            }, false);

            window.addEventListener('touchmove', function(e){
                game.touchmove(e);
            }, false);

            function toggleMute() {
                game.mute();
                document.getElementById("muteLink").innerText = game.sounds.mute ? "unmute" : "mute";
            }
        </script>

monitor-ui/src/Covid19.Monitor.Ui/Views/Supply/Index.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

@section Scripts
{
    <script>
        window.services = window.services || {};
        window.services.backend = '@Configuration["BackendUrl"]';
    </script>
    <script src="~/js/supply.js" asp-append-version="true"></script>
}

@{
    ViewData["Icon"] = "fa-pump-soap";
    ViewData["Title"] = "Suprimentos";
}

<h4>Mapeamento de venda de suprimentos</h4>

<p>
    A lista abaixo reflete um mapeamento de suprimentos em várias lojas online.
    Os preços abaixo são monitorados e atualizados diáriamente
</p>

<div id="preloader" class="alert alert-primary text-center" role="alert" style="display: none">
    <img src="img/Spinner-0.4s-30px.gif" alt="" title=""/>
    Arguarde enquando a listagem é montada ...
</div>

<div id="results" class="row row-cols-1 row-cols-md-3"></div>